In [13]:
class Employee:
    # Class variable to keep track of the number of employees
    employee_count = 0
    total_salary = 0
    
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.employee_count += 1
        Employee.total_salary += salary
    
    @staticmethod
    def average_salary():
        if Employee.employee_count == 0:
            return 0
        return Employee.total_salary / Employee.employee_count
    
    def display_info(self):
        return f"Name: {self.name}, Family: {self.family}, Salary: {self.salary}, Department: {self.department}"


class FulltimeEmployee(Employee):
    def __init__(self, name, family, salary, department, benefits):
        super().__init__(name, family, salary, department)
        self.benefits = benefits
    
    def display_info(self):
        basic_info = super().display_info()
        return f"{basic_info}, Benefits: {self.benefits}"


# Creating instances of Employee and FulltimeEmployee
emp1 = Employee("dulquer salman", "salman Family", 580000, "Engineering")
emp2 = Employee("bheem kim", "kim Family", 670000, "Marketing")

fulltime_emp1 = FulltimeEmployee("Alice Johnson", "Johnson Family", 670000, "Design", "Health Insurance")

# Displaying employee information
print(emp1.display_info())
print(emp2.display_info())
print(fulltime_emp1.display_info())

# Calculating and displaying the average salary
print(f"Average Salary: ${Employee.average_salary():.2f}")

# Display the total number of employees
print(f"Total Number of Employees: {Employee.employee_count}")


Name: dulquer salman, Family: salman Family, Salary: 580000, Department: Engineering
Name: bheem kim, Family: kim Family, Salary: 670000, Department: Marketing
Name: Alice Johnson, Family: Johnson Family, Salary: 670000, Department: Design, Benefits: Health Insurance
Average Salary: $640000.00
Total Number of Employees: 3


In [15]:
import numpy as np

# Step 1: Create a random vector of size 20 with float values in the range 1-20
vector = np.random.uniform(1, 20, size=20)

# Step 2: Reshape the vector to a 4x5 matrix
matrix = vector.reshape(4, 5)

# Step 3: Replace the maximum value in each row with 0
# Find the index of the maximum value in each row
max_indices = np.argmax(matrix, axis=1)

# Create an array of zeros with the same shape as matrix
result = np.copy(matrix)

# Replace the maximum values with 0 using advanced indexing
result[np.arange(matrix.shape[0]), max_indices] = 0

# Print the original matrix and the result
print("Original Matrix:\n", matrix)
print("Result Matrix (with max values replaced by 0):\n", result)


Original Matrix:
 [[ 2.52130222  4.43218392  2.46095454 13.27738095 13.7236199 ]
 [18.01942264 11.24905276  5.44297275  4.94171971 16.54301944]
 [ 9.86236494  1.5520873  13.15034356 13.35127859 15.87764277]
 [ 1.62082114  4.53887017  8.63530883  4.51587228 14.95167714]]
Result Matrix (with max values replaced by 0):
 [[ 2.52130222  4.43218392  2.46095454 13.27738095  0.        ]
 [ 0.         11.24905276  5.44297275  4.94171971 16.54301944]
 [ 9.86236494  1.5520873  13.15034356 13.35127859  0.        ]
 [ 1.62082114  4.53887017  8.63530883  4.51587228  0.        ]]
